// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const allContacts = `-- name: AllContacts :many
SELECT user_id, name, phone, email, address FROM contacts WHERE user_id = $1
`

type AllContactsRow struct {
	UserID  uuid.UUID
	Name    string
	Phone   string
	Email   string
	Address string
}

func (q *Queries) AllContacts(ctx context.Context, userID uuid.UUID) ([]AllContactsRow, error) {
	rows, err := q.db.Query(ctx, allContacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllContactsRow
	for rows.Next() {
		var i AllContactsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findContactByName = `-- name: FindContactByName :one
SELECT user_id, name, phone, email, address FROM contacts WHERE user_id = $1 AND name = $2
`

type FindContactByNameParams struct {
	UserID uuid.UUID
	Name   string
}

type FindContactByNameRow struct {
	UserID  uuid.UUID
	Name    string
	Phone   string
	Email   string
	Address string
}

func (q *Queries) FindContactByName(ctx context.Context, arg FindContactByNameParams) (FindContactByNameRow, error) {
	row := q.db.QueryRow(ctx, findContactByName, arg.UserID, arg.Name)
	var i FindContactByNameRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
	)
	return i, err
}

const removeContact = `-- name: RemoveContact :exec
DELETE FROM contacts WHERE user_id = $1 AND name = $2
`

type RemoveContactParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) RemoveContact(ctx context.Context, arg RemoveContactParams) error {
	_, err := q.db.Exec(ctx, removeContact, arg.UserID, arg.Name)
	return err
}

const saveContact = `-- name: SaveContact :exec
INSERT INTO contacts (user_id, name, phone, email, address) VALUES ($1, $2, $3, $4, $5)
`

type SaveContactParams struct {
	UserID  uuid.UUID
	Name    string
	Phone   string
	Email   string
	Address string
}

func (q *Queries) SaveContact(ctx context.Context, arg SaveContactParams) error {
	_, err := q.db.Exec(ctx, saveContact,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
	)
	return err
}
