// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	uuid "github.com/google/uuid"
)

type Contact struct {
	Name    string
	Phone   string
	Email   string
	Address string
	UserID  uuid.UUID
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
}
