// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	AllContacts(ctx context.Context, userID uuid.UUID) ([]AllContactsRow, error)
	FindContactByName(ctx context.Context, arg FindContactByNameParams) (FindContactByNameRow, error)
	RemoveContact(ctx context.Context, arg RemoveContactParams) error
	SaveContact(ctx context.Context, arg SaveContactParams) error
}

var _ Querier = (*Queries)(nil)
