// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: auth.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authFindUserByEmail = `-- name: AuthFindUserByEmail :one
SELECT id, email, name, password_hash, is_active, created_at
FROM users WHERE email = $1
`

type AuthFindUserByEmailRow struct {
	ID           pgtype.UUID
	Email        string
	Name         string
	PasswordHash string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) AuthFindUserByEmail(ctx context.Context, email string) (AuthFindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, authFindUserByEmail, email)
	var i AuthFindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const authFindUserByID = `-- name: AuthFindUserByID :one
SELECT id, email, name, password_hash, is_active, created_at
FROM users WHERE id = $1
`

type AuthFindUserByIDRow struct {
	ID           pgtype.UUID
	Email        string
	Name         string
	PasswordHash string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) AuthFindUserByID(ctx context.Context, id pgtype.UUID) (AuthFindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, authFindUserByID, id)
	var i AuthFindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const findRefreshToken = `-- name: FindRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked_at
FROM refresh_tokens WHERE token_hash = $1
`

type FindRefreshTokenRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) FindRefreshToken(ctx context.Context, tokenHash string) (FindRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, findRefreshToken, tokenHash)
	var i FindRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const loadRolesForAuthUser = `-- name: LoadRolesForAuthUser :many
SELECT r.id, r.name
FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

type LoadRolesForAuthUserRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) LoadRolesForAuthUser(ctx context.Context, userID pgtype.UUID) ([]LoadRolesForAuthUserRow, error) {
	rows, err := q.db.Query(ctx, loadRolesForAuthUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadRolesForAuthUserRow
	for rows.Next() {
		var i LoadRolesForAuthUserRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const saveRefreshToken = `-- name: SaveRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type SaveRefreshTokenParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, saveRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}
