// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignRole(ctx context.Context, arg AssignRoleParams) error
	AuthFindUserByEmail(ctx context.Context, email string) (AuthFindUserByEmailRow, error)
	AuthFindUserByID(ctx context.Context, id pgtype.UUID) (AuthFindUserByIDRow, error)
	CountActiveSystemRoleUsers(ctx context.Context) (int32, error)
	CountUsersWithRole(ctx context.Context, roleID pgtype.UUID) (int32, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeletePermissionsForRole(ctx context.Context, roleID pgtype.UUID) error
	DeleteRole(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteUserRoles(ctx context.Context, userID pgtype.UUID) error
	FindRefreshToken(ctx context.Context, tokenHash string) (FindRefreshTokenRow, error)
	FindRoleByID(ctx context.Context, id pgtype.UUID) (FindRoleByIDRow, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertPermission(ctx context.Context, arg InsertPermissionParams) error
	ListRoles(ctx context.Context) ([]ListRolesRow, error)
	LoadPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]LoadPermissionsForRoleRow, error)
	LoadRolesForAuthUser(ctx context.Context, userID pgtype.UUID) ([]LoadRolesForAuthUserRow, error)
	LoadRolesForUser(ctx context.Context, userID pgtype.UUID) ([]LoadRolesForUserRow, error)
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error
	SetActive(ctx context.Context, arg SetActiveParams) (int64, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (int64, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
