// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: roles.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersWithRole = `-- name: CountUsersWithRole :one
SELECT COUNT(*)::int FROM user_roles WHERE role_id = $1
`

func (q *Queries) CountUsersWithRole(ctx context.Context, roleID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUsersWithRole, roleID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (id, name, description, is_system) VALUES ($1, $2, $3, $4)
`

type CreateRoleParams struct {
	ID          pgtype.UUID
	Name        string
	Description *string
	IsSystem    bool
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsSystem,
	)
	return err
}

const deletePermissionsForRole = `-- name: DeletePermissionsForRole :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeletePermissionsForRole(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePermissionsForRole, roleID)
	return err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findRoleByID = `-- name: FindRoleByID :one
SELECT id, name, COALESCE(description, '') AS description, is_system, created_at, updated_at
FROM roles WHERE id = $1
`

type FindRoleByIDRow struct {
	ID          pgtype.UUID
	Name        string
	Description string
	IsSystem    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) FindRoleByID(ctx context.Context, id pgtype.UUID) (FindRoleByIDRow, error) {
	row := q.db.QueryRow(ctx, findRoleByID, id)
	var i FindRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPermission = `-- name: InsertPermission :exec
INSERT INTO role_permissions (id, role_id, resource, action)
VALUES ($1, $2, $3, $4)
`

type InsertPermissionParams struct {
	ID       pgtype.UUID
	RoleID   pgtype.UUID
	Resource string
	Action   string
}

func (q *Queries) InsertPermission(ctx context.Context, arg InsertPermissionParams) error {
	_, err := q.db.Exec(ctx, insertPermission,
		arg.ID,
		arg.RoleID,
		arg.Resource,
		arg.Action,
	)
	return err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, COALESCE(description, '') AS description, is_system, created_at, updated_at
FROM roles ORDER BY name
`

type ListRolesRow struct {
	ID          pgtype.UUID
	Name        string
	Description string
	IsSystem    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadPermissionsForRole = `-- name: LoadPermissionsForRole :many
SELECT resource, action FROM role_permissions
WHERE role_id = $1 ORDER BY resource, action
`

type LoadPermissionsForRoleRow struct {
	Resource string
	Action   string
}

func (q *Queries) LoadPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]LoadPermissionsForRoleRow, error) {
	rows, err := q.db.Query(ctx, loadPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadPermissionsForRoleRow
	for rows.Next() {
		var i LoadPermissionsForRoleRow
		if err := rows.Scan(&i.Resource, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE roles SET name = $1, description = $2 WHERE id = $3
`

type UpdateRoleParams struct {
	Name        string
	Description *string
	ID          pgtype.UUID
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRole, arg.Name, arg.Description, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
