// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2)
`

type AssignRoleParams struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.RoleID)
	return err
}

const countActiveSystemRoleUsers = `-- name: CountActiveSystemRoleUsers :one
SELECT COUNT(DISTINCT u.id)::int
FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles ro ON ro.id = ur.role_id
WHERE u.is_active = true AND ro.is_system = true
`

func (q *Queries) CountActiveSystemRoleUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveSystemRoleUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, name, password_hash, is_active)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Email        string
	Name         string
	PasswordHash string
	IsActive     bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.IsActive,
	)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, name, password_hash, is_active, created_at, updated_at
FROM users WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, name, password_hash, is_active, created_at, updated_at
FROM users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const loadRolesForUser = `-- name: LoadRolesForUser :many
SELECT ro.id, ro.name, ro.is_system
FROM roles ro
JOIN user_roles ur ON ur.role_id = ro.id
WHERE ur.user_id = $1 ORDER BY ro.name
`

type LoadRolesForUserRow struct {
	ID       pgtype.UUID
	Name     string
	IsSystem bool
}

func (q *Queries) LoadRolesForUser(ctx context.Context, userID pgtype.UUID) ([]LoadRolesForUserRow, error) {
	rows, err := q.db.Query(ctx, loadRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadRolesForUserRow
	for rows.Next() {
		var i LoadRolesForUserRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsSystem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActive = `-- name: SetActive :execrows
UPDATE users SET is_active = $1 WHERE id = $2
`

type SetActiveParams struct {
	IsActive bool
	ID       pgtype.UUID
}

func (q *Queries) SetActive(ctx context.Context, arg SetActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setActive, arg.IsActive, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePassword = `-- name: UpdatePassword :execrows
UPDATE users SET password_hash = $1 WHERE id = $2
`

type UpdatePasswordParams struct {
	PasswordHash string
	ID           pgtype.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users SET email = $1, name = $2 WHERE id = $3
`

type UpdateUserParams struct {
	Email string
	Name  string
	ID    pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser, arg.Email, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
